name: Publish release package

on:
  workflow_dispatch:
    inputs:
      token:
        description: 'Publish release token'
        required: true
        type: string

permissions:
  contents: write
  packages: write

jobs:
  build-and-publish-release:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    if: github.ref_name != 'main'
    steps:
      - name: Check release token
        run: |
          if [ "${{ github.event.inputs.token }}" != ${{ secrets.RELEASE_TOKEN }} ]; then
            echo "Invalid release token provided."
            exit 1
          fi

      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' 
          distribution: 'temurin'

      - name: Build 
        run: |
          mvn package -DskipTests
      - name: List dist directory
        run: ls -R target/package

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          body: "Automated release for commit ${{ github.ref_name }}"
          draft: false
          prerelease: false
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: target/package/*.zip*
          tag: ${{ github.ref }}
